"""Pydantic request/response models for the API, split by domain
(2026-08-28 repo cleanup — was one 445-line `schemas.py`). Every name is
re-exported here so every existing `from app.api.schemas import X` call
site keeps working unchanged; new code can still import from the specific
submodule (`app.api.schemas.groups`, etc.) if that reads better."""

from app.api.schemas.annotations import (
    AnnotationCreate,
    AnnotationOut,
    AnnotationShareCreate,
    AnnotationShareOut,
    AnnotationUpdate,
)
from app.api.schemas.auth import (
    MIN_PASSWORD_LENGTH,
    ChangePasswordRequest,
    ForgotPasswordRequest,
    OAuthProviderStatusOut,
    ResetPasswordRequest,
    Token,
    UserCreate,
    UserLogin,
    UserOut,
    UserUpdate,
)
from app.api.schemas.groups import (
    GroupCreate,
    GroupDescriptionUpdate,
    GroupGuestSettingsUpdate,
    GroupMemberAdd,
    GroupMemberOut,
    GroupMemberRoleUpdate,
    GroupMemberTitleUpdate,
    GroupOut,
    GroupPageSettingOut,
    GroupPageSettingsUpdate,
    GroupPageSettingUpdate,
    GroupRehearsalScheduleUpdate,
)
from app.api.schemas.homework import HomeworkCreate, HomeworkOut
from app.api.schemas.library import (
    DistributionOut,
    GuestGroupOut,
    GuestPieceOut,
    LibraryEntryOut,
    PieceDefaultTempoUpdate,
    PieceDetailsUpdate,
    PieceOut,
    PieceUploadOut,
    PieceVersionOut,
    RenderManifestOut,
    TimeSignatureOut,
)
from app.api.schemas.omr import OmrImportOut, OmrImportRequest, OmrJobOut
from app.api.schemas.piece_markup import MarkupMarkCreate, MarkupMarkOut
from app.api.schemas.responsibilities import (
    ResponsibilityDateCreate,
    ResponsibilityDateOut,
    ResponsibilityDateUpdate,
    ResponsibilityGuestDateOut,
    ResponsibilityGuestRoleCoverageOut,
    ResponsibilityRoleCoverageOut,
    ResponsibilityRoleCreate,
    ResponsibilityRoleOut,
    ResponsibilityRoleUpdate,
    ResponsibilityScheduleCreate,
    ResponsibilityScheduleOut,
    ResponsibilityScheduleUpdate,
    ResponsibilitySignupCreate,
    ResponsibilitySignupOut,
)
from app.api.schemas.weekly_notes import WeeklyNoteCreate, WeeklyNoteOut, WeeklyNoteUpdate

__all__ = [
    "MIN_PASSWORD_LENGTH",
    "AnnotationCreate",
    "AnnotationOut",
    "AnnotationShareCreate",
    "AnnotationShareOut",
    "AnnotationUpdate",
    "ChangePasswordRequest",
    "DistributionOut",
    "ForgotPasswordRequest",
    "GroupCreate",
    "GroupDescriptionUpdate",
    "GroupGuestSettingsUpdate",
    "GroupMemberAdd",
    "GroupMemberOut",
    "GroupMemberRoleUpdate",
    "GroupMemberTitleUpdate",
    "GroupOut",
    "GroupPageSettingOut",
    "GroupPageSettingUpdate",
    "GroupPageSettingsUpdate",
    "GroupRehearsalScheduleUpdate",
    "GuestGroupOut",
    "GuestPieceOut",
    "HomeworkCreate",
    "HomeworkOut",
    "LibraryEntryOut",
    "MarkupMarkCreate",
    "MarkupMarkOut",
    "OAuthProviderStatusOut",
    "OmrImportOut",
    "OmrImportRequest",
    "OmrJobOut",
    "PieceDefaultTempoUpdate",
    "PieceOut",
    "PieceUploadOut",
    "PieceVersionOut",
    "RenderManifestOut",
    "ResetPasswordRequest",
    "ResponsibilityDateCreate",
    "ResponsibilityDateOut",
    "ResponsibilityDateUpdate",
    "ResponsibilityGuestDateOut",
    "ResponsibilityGuestRoleCoverageOut",
    "ResponsibilityRoleCoverageOut",
    "ResponsibilityRoleCreate",
    "ResponsibilityRoleOut",
    "ResponsibilityRoleUpdate",
    "ResponsibilityScheduleCreate",
    "ResponsibilityScheduleOut",
    "ResponsibilityScheduleUpdate",
    "ResponsibilitySignupCreate",
    "ResponsibilitySignupOut",
    "TimeSignatureOut",
    "Token",
    "UserCreate",
    "UserLogin",
    "UserOut",
    "UserUpdate",
    "WeeklyNoteCreate",
    "WeeklyNoteOut",
    "WeeklyNoteUpdate",
]
