"""Pydantic request/response models for the API, split by domain
(2026-08-28 repo cleanup — was one 445-line `schemas.py`). Every name is
re-exported here so every existing `from app.api.schemas import X` call
site keeps working unchanged; new code can still import from the specific
submodule (`app.api.schemas.groups`, etc.) if that reads better."""

from app.api.schemas.annotations import (
    AnnotationCreate,
    AnnotationOut,
    AnnotationShareCreate,
    AnnotationShareOut,
    AnnotationUpdate,
)
from app.api.schemas.auth import (
    MIN_PASSWORD_LENGTH,
    ChangePasswordRequest,
    ForgotPasswordRequest,
    OAuthProviderStatusOut,
    ParticipantNameUpdate,
    ResetPasswordRequest,
    Token,
    UserCreate,
    UserLogin,
    UserOut,
    UserUpdate,
)
from app.api.schemas.groups import (
    GroupCreate,
    GroupDescriptionUpdate,
    GroupGuestSettingsUpdate,
    GroupMemberAdd,
    GroupMemberOut,
    GroupMemberRoleUpdate,
    GroupMemberTitleUpdate,
    GroupOut,
    GroupPageSettingOut,
    GroupPageSettingsUpdate,
    GroupPageSettingUpdate,
    GroupRehearsalScheduleUpdate,
)
from app.api.schemas.carpool import (
    CarpoolEventCreate,
    CarpoolEventOut,
    CarpoolEventUpdate,
    CarpoolPostCreate,
    CarpoolPostOut,
    CarpoolPostUpdate,
)
from app.api.schemas.custom_pages import GroupCustomPageCreate, GroupCustomPageOut, GroupCustomPageUpdate
from app.api.schemas.homework import HomeworkCreate, HomeworkOut, HomeworkUpdate
from app.api.schemas.library import (
    AdminPreviewOut,
    DistributionOut,
    GuestAuthIn,
    GuestAuthOut,
    GuestGroupOut,
    GuestNameMatchOut,
    GuestPieceOut,
    GuestPieceOwnerOut,
    LibraryEntryOut,
    PieceDefaultTempoUpdate,
    PieceDetailsUpdate,
    PieceOut,
    PieceUploadOut,
    PieceVersionOut,
    RenderManifestOut,
    TimeSignatureOut,
    VersionPublishRequest,
    WorkingDraftOut,
)
from app.api.schemas.omr import (
    OmrImportOut,
    OmrImportRequest,
    OmrJobListItemOut,
    OmrJobOut,
    OmrPageRerunOut,
)
from app.api.schemas.piece_markup import MarkupMarkCreate, MarkupMarkOut, MarkupMarkUpdate
from app.api.schemas.piece_rehearsal_notes import (
    PieceRehearsalNoteCreate,
    PieceRehearsalNoteOut,
    PieceRehearsalNoteUpdate,
)
from app.api.schemas.responsibilities import (
    ResponsibilityDateCreate,
    ResponsibilityDateOut,
    ResponsibilityDateScheduleAttach,
    ResponsibilityDateScheduleGroupOut,
    ResponsibilityDateUpdate,
    ResponsibilityGuestDateOut,
    ResponsibilityGuestRoleCoverageOut,
    ResponsibilityGuestScheduleGroupOut,
    ResponsibilityGuestSignupOut,
    ResponsibilityRoleCoverageOut,
    ResponsibilityRoleCreate,
    ResponsibilityRoleOut,
    ResponsibilityRoleUpdate,
    ResponsibilityScheduleCreate,
    ResponsibilityScheduleOut,
    ResponsibilityScheduleUpdate,
    ResponsibilitySignupCreate,
    ResponsibilitySignupOut,
)
from app.api.schemas.weekly_notes import WeeklyNoteCreate, WeeklyNoteOut, WeeklyNoteUpdate

__all__ = [
    "MIN_PASSWORD_LENGTH",
    "AdminPreviewOut",
    "AnnotationCreate",
    "CarpoolEventCreate",
    "CarpoolEventOut",
    "CarpoolEventUpdate",
    "CarpoolPostCreate",
    "CarpoolPostOut",
    "CarpoolPostUpdate",
    "AnnotationOut",
    "AnnotationShareCreate",
    "AnnotationShareOut",
    "AnnotationUpdate",
    "ChangePasswordRequest",
    "DistributionOut",
    "ForgotPasswordRequest",
    "GroupCreate",
    "GroupCustomPageCreate",
    "GroupCustomPageOut",
    "GroupCustomPageUpdate",
    "GroupDescriptionUpdate",
    "GroupGuestSettingsUpdate",
    "GroupMemberAdd",
    "GroupMemberOut",
    "GroupMemberRoleUpdate",
    "GroupMemberTitleUpdate",
    "GroupOut",
    "GroupPageSettingOut",
    "GroupPageSettingUpdate",
    "GroupPageSettingsUpdate",
    "GroupRehearsalScheduleUpdate",
    "GuestAuthIn",
    "GuestAuthOut",
    "GuestGroupOut",
    "GuestNameMatchOut",
    "GuestPieceOut",
    "GuestPieceOwnerOut",
    "HomeworkCreate",
    "HomeworkOut",
    "HomeworkUpdate",
    "LibraryEntryOut",
    "MarkupMarkCreate",
    "MarkupMarkOut",
    "MarkupMarkUpdate",
    "OAuthProviderStatusOut",
    "OmrImportOut",
    "OmrImportRequest",
    "OmrJobListItemOut",
    "OmrJobOut",
    "OmrPageRerunOut",
    "ParticipantNameUpdate",
    "PieceDefaultTempoUpdate",
    "PieceDetailsUpdate",
    "PieceOut",
    "PieceRehearsalNoteCreate",
    "PieceRehearsalNoteOut",
    "PieceRehearsalNoteUpdate",
    "PieceUploadOut",
    "PieceVersionOut",
    "RenderManifestOut",
    "VersionPublishRequest",
    "WorkingDraftOut",
    "ResetPasswordRequest",
    "ResponsibilityDateCreate",
    "ResponsibilityDateOut",
    "ResponsibilityDateScheduleAttach",
    "ResponsibilityDateScheduleGroupOut",
    "ResponsibilityDateUpdate",
    "ResponsibilityGuestDateOut",
    "ResponsibilityGuestRoleCoverageOut",
    "ResponsibilityGuestScheduleGroupOut",
    "ResponsibilityGuestSignupOut",
    "ResponsibilityRoleCoverageOut",
    "ResponsibilityRoleCreate",
    "ResponsibilityRoleOut",
    "ResponsibilityRoleUpdate",
    "ResponsibilityScheduleCreate",
    "ResponsibilityScheduleOut",
    "ResponsibilityScheduleUpdate",
    "ResponsibilitySignupCreate",
    "ResponsibilitySignupOut",
    "TimeSignatureOut",
    "Token",
    "UserCreate",
    "UserLogin",
    "UserOut",
    "UserUpdate",
    "WeeklyNoteCreate",
    "WeeklyNoteOut",
    "WeeklyNoteUpdate",
]
